Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
     
    config.vm.define "topaze" do |topaze|
	topaze.vm.hostname = "topaze"
#    topaze.vm.network "public_network", bridge: "enp1s2"
	topaze.vm.network "forwarded_port", guest: 80, host: 8081
	topaze.vm.network "public_network", bridge: "enp1s2", ip: "10.10.10.10"	
	topaze.vm.synced_folder "./conf", "/home/vagrant/conf" 
	
	topaze.vm.provision "shell",
	inline: <<-SHELL
		apt-get update
        apt-get -y upgrade
        apt-get install -y curl net-tools bash-completion wget lsof
        
        echo "order hosts,bind\nmulti on" > /etc/host.conf
        hostnamectl set-hostname mail.syssko.iut
        echo "10.14.0.3 syssko.iut mail.syssko.iut" >> /etc/hosts
        ### normalement faut redemarer mais tkt
        
        ##instalation de postfix en mode non interactif
        DEBIAN_FRONTEND=noninteractive apt-get install -y postfix
        echo "postfix postfix/main_mailer_type select Internet Site" | sudo debconf-set-selections
        echo "postfix postfix/mailname string syssko.iut" | sudo debconf-set-selections
        dpkg-reconfigure -f noninteractive postfix
        cp /etc/postfix/main.cf{,.backup}
        cp /home/vagrant/conf/main.cf /etc/postfix/
        systemctl restart postfix

        apt-get install -y mailutils
        apt install -y dovecot-core dovecot-imapd
        cp /home/vagrant/conf/dovecot.conf /etc/dovecot/dovecot.conf
        cp /home/vagrant/conf/10-auth.conf /etc/dovecot/conf.d/10-auth.conf
        cp /home/vagrant/conf/10-mail.conf /etc/dovecot/conf.d/10-mail.conf
        cp /home/vagrant/conf/10-master.conf /etc/dovecot/conf.d/10-master.conf
        systemctl restart dovecot.service 

        apt install -y apache2 php libapache2-mod-php php-curl php-xml
        cd /var/www/html/
        rm index.html
        curl -sL https://repository.rainloop.net/installer.php | php

		#mkdir -p /var/www/html/data/_data_/_default_/domains
        #cp /home/vagrant/conf/syssko.iut.ini /var/www/html/data/_data_/_default_/domains/

        reboot
        
    SHELL
  #web 
  end
end
