Vagrant.configure("2") do |config|
  
    config.vm.box = "debian/bookworm64"

    config.vm.define "dhcp" do |dhcp|
      dhcp.vm.hostname = "dhcp"
      dhcp.vm.network "public_network",bridge: "enp1s2", ip:"192.168.21.250", netmask: "255.255.255.0"
      dhcp.vm.provision "file", source: "config/dhcp/dhcpd.conf",destination: "/tmp/"
      dhcp.vm.provision "file", source: "config/dhcp/isc-dhcp-server",destination: "/tmp/"      
      dhcp.vm.provision "shell", inline: <<-SHELL
        apt update -y
        apt install -y isc-dhcp-server
        cp -f /tmp/dhcpd.conf /etc/dhcp/
        cp -f /tmp/isc-dhcp-server /etc/default/
        systemctl restart isc-dhcp-server
        ip route del default via 10.0.2.2
        ip route add default via 192.168.21.1 dev eth1
      SHELL
    end
 
end