Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"

    config.vm.define "proxy" do |proxy|
      proxy.vm.hostname = "proxy"
      proxy.vm.network "public_network",bridge: "enp1s2", ip:"192.168.21.252", netmask: "255.255.255.0"
      proxy.vm.provision "file", source: "squid.conf", destination: "/tmp/"
      proxy.vm.provision "shell", inline: <<-SHELL
        apt update -y
        apt install -y squid
        cp /tmp/squid.conf /etc/squid/squid.conf
        systemctl restart squid
        ip route del default via 10.0.2.2
        ip route add default via 192.168.21.1 dev eth1
      SHELL
    end

end

