Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  config.vm.define "srvpub" do |srvpub|
    srvpub.vm.hostname = "srvpub"
    srvpub.vm.network "public_network", bridge: "enp1s2", ip: "10.10.10.18", netmask: "255.255.255.248"
    srvpub.vm.provision "shell", inline: <<-SHELL
        apt-get update && apt-get upgrade -y 
        apt-get install bind9 -y
	ip route del default via 10.0.0.2 dev eth0
	ip route add default via 10.10.10.22 dev eth1
        cp -r /vagrant/bind/* /etc/bind/
	cp /vagrant/resolv.conf /etc/
        systemctl restart bind9
    SHELL
  end

end
