Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  
    config.vm.define 'Iolite' do |serveur|
    iolite.vm.hostname = "Iolite"
    iolite.vm.network "private_network", ip: "192.168.60.30", netmask: "255.255.255.0"
    iolite.vm.disk :disk, name: "disk1", size: "5GB"
    iolite.vm.disk :disk, name: "disk2", size: "5GB"                              
    iolite.vm.disk :disk, name: "disk3", size: "5GB"                              
    iolite.vm.disk :disk, name: "disk4", size: "5GB" 
      
    iolite.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y mdadm nfs-kernel-server samba
        mdadm --create /dev/md0 --level=5 --raid-devices=3 /dev/sdb /dev/sdc /dev/sdd --spare-device=1 /dev/sde
        mkfs.ext4 /dev/md0
        mkdir /home/RAID
        mount /dev/md0 /home/RAID
        systemctl daemon-reload
        echo "/home   192.168.60.0/24(rw,root_squash,no_subtree_check)" >> /etc/exports
        echo "/var/share/public       192.168.60.0/24(ro,all_squash,no_subtree_check)" >> /etc/exports
        echo "/var/share/public       192.168.70.0/24(ro,all_squash,no_subtree_check)" >> /etc/exports
        echo "/var/share/public       192.168.80.0/24(ro,all_squash,no_subtree_check)" >> /etc/exports
        echo "/var/share/root         192.168.60.50(rw,no_root_squash,no_subtree_check)" >> /etc/exports
        
        mkdir /var/share
        mkdir /var/share/root
        mkdir /var/share/public
  
        mkdir /srv/samba
        mkdir /srv/samba/public_ro
        mkdir /srv/samba/public_rw
        mkdir /srv/samba/public_full
  
        mount -a
  
        systemctl start nfs-kernel-server
      SHELL
    end
end