Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "nfs" do |nfs|
	nfs.vm.hostname = "nfs"
	nfs.vm.network "public_network", bridge:"enp1s2",ip: "192.168.12.253",netmask:"255.255.255.0"

	nfs.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update
		sudo apt-get install -y nfs-kernel-server
		sudo echo "/home/ 192.168.0.0/16(rw,sync,subtree_check)" >> /etc/exports 
		sudo exportfs -a
		sudo chmod 757 /home
		sudo service nfs-kernel-server reload
  SHELL
  end
end
