Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
  
    config.vm.define "client" do |client|
      client.vm.network "public_network",bridge:"enp1s2"
      client.vm.hostname = "client"
      client.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y nfs-common chromium chromium-l10n thunderbird-l10n-fr
      sudo echo "192.168.12.253:/home/    /home   nfs     rw,hard,intr      0       0" >> /etc/fstab
      sudo ip route del default via 10.0.2.2 dev eth0
      sudo ip route add default via 192.168.12.1 dev eth1
      cp /vagrant/resolv.conf /etc/
      SHELL
    end
  end
  