Vagrant.configure("2") do |config|
  config.vm.define 'dhcp' do |dhcp|
    dhcp.vm.box = "debian/bookworm64"
    dhcp.vm.network "public_network", bridge: "enp1s2", ip: "192.168.12.254", netmask: "255.255.255.0"
    dhcp.vm.hostname = "dhcp"
    dhcp.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y isc-dhcp-server
      ip route del default via 10.0.2.2 dev eth0
      ip route add default via 192.168.12.1 dev eth1
      sed -i 's/INTERFACESv4=""/INTERFACESv4="eth1"/' /etc/default/isc-dhcp-server
      cp /vagrant/dhcp/dhcpd.conf /etc/dhcp/
      cp /vagrant/resolv.conf /etc/
      systemctl restart isc-dhcp-server
    SHELL
  end
end
