Vagrant.configure("2") do |config|

    config.vm.box = "debian/bookworm64"

  config.vm.define "web" do |web|
    web.vm.network "public_network", bridge: "enp1s2", ip: "10.10.10.17", netmask: "255.255.255.249"
    web.vm.network :forwarded_port, guest:80, host: 8086
    web.vm.synced_folder "./conf", "/home/vagrant/conf/" 
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update 
      sudo apt-get install apache2 -y 
      ip route del default via 10.0.0.2 dev eth0
	    ip route add default via 10.10.10.22 dev eth1
      rm /var/www/html/index.html
      cp /home/vagrant/conf/index-techtonic.html /var/www/html/index.html
	  
    SHELL

  end


end
