# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bookworm64"
  #config.vm.synced_folder ".", "/vagrant"
  #config.vm.network "public_network", bridge: "enp1s2", ip: "192.168.24.52", netmask: "255.255.0.0"

  config.vm.define "ldap" do |ldap|
    ldap.vm.synced_folder ".", "/vagrant"
    ldap.vm.network "private_network", ip: "192.168.60.52"
    ldap.vm.hostname = "capsule.iut"
    ldap.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
    SHELL
  end

  config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"
    nfs.vm.network "private_network", ip: "192.168.60.55"
    nfs.vm.provision "shell", inline: <<-SHELL
      apt update
      mkdir /home/nfs_home
      apt install -y nfs-kernel-server
#      chmod 757 /home/nfs_home
      echo "/home/nfs_home/ 192.168.0.0/16(rw,sync,no_subtree_check)" >> /etc/exports
      exportfs -a
      systemctl reload nfs-kernel-server
    SHELL
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.60.53"
    client.vm.hostname = "client"
    client.vm.provision "file", source: "bin/nfs_mount.sh", destination: "/tmp/"
    client.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
      source /tmp/nfs_mount.sh
    SHELL
  end

#  config.vm.define "client2" do |client2|
#    client2.vm.network "private_network", ip: "192.168.60.54"
#    client2.vm.hostname = "client2"
#    client2.vm.provision "file", source: "bin/nfs_mount.sh", destination: "/tmp/"
#    client2.vm.provision "shell", inline: <<-SHELL
#      apt-get -y update && apt-get -y upgrade
#      source /tmp/nfs_mount.sh
#    SHELL
#  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
