Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provision "file", source: "resolv.conf", destination:"/tmp/"
  
  config.vm.define "ldap" do |ldap|
    ldap.vm.synced_folder ".", "/vagrant"
    ldap.vm.network "public_network",bridge: "enp1s2", ip:"192.168.21.253", netmask: "255.255.255.0"
    ldap.vm.hostname = "ldap"
    ldap.vm.provision "shell", inline: <<-SHELL
      apt update
      ip route del default
      ip route add default via 192.168.21.1
      cp /tmp/resolv.conf /etc/
      cp /vagrant/ldap_tree/{structure.ldif,people.ldif} .
      cp /vagrant/bin/ldap_server.sh .
    SHELL
  end

  config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"
    nfs.vm.network "public_network",bridge: "enp1s2", ip:"192.168.21.249", netmask: "255.255.255.0"
    nfs.vm.provision "shell", inline: <<-SHELL
      apt update
      mkdir /home/nfs_home
      apt install -y nfs-kernel-server
#      chmod 757 /home
      echo "/home/nfs_home/ 192.168.0.0/16(rw,sync,no_subtree_check)" >> /etc/exports
      exportfs -a
      systemctl reload nfs-kernel-server
      ip route del default
      ip route add default via 192.168.21.1
      cp /tmp/resolv.conf /etc/
      echo "session     required      pam_mkhomedir.so skel=/etc/skel umask=0022" >> /etc/pam.d/common-session
    SHELL
  end
end
