Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.define "glpi" do |glpi|
    glpi.vm.network "public_network", bridge: "enp1s2", ip: "172.16.50.10", netmask: "255.255.255.0"
    glpi.vm.hostname = "glpi"
    glpi.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 mariadb-server php-ldap php-imap php-apcu php-xmlrpc php-cas php-mysqli php-mbstring php-curl php-gd php-simplexml php-xml php-intl php-zip php-bz2 perl
      wget https://github.com/glpi-project/glpi/releases/download/10.0.10/glpi-10.0.10.tgz
      tar -xzf glpi-10.0.10.tgz -C /var/www/html
      chown -R www-data:www-data /var/www/html/glpi && chmod -R 775 /var/www/html/glpi
      mysql -uroot -pa -e "create database glpi;"
      mysql -uroot -pa -e "create user glpi@localhost identified by 'mandarine';"
      mysql -uroot -pa -e "grant all privileges on glpi.* to glpi@localhost;"
      mysql -uroot -pa -e "flush privileges;"
      cp /vagrant/apache_conf_glpi /etc/apache2/sites-enabled/000-default.conf
      systemctl restart apache2 mysql
    SHELL
    glpi.vm.provision "shell", run: "always", inline: "route add default gw 172.16.50.254"
  end

  config.vm.define "nginx" do |nginx|
    nginx.vm.network "public_network", bridge: "enp1s2", ip: "172.16.50.20", netmask: "255.255.255.0"
    nginx.vm.network "forwarded_port", host: 8080, guest: 8080
    nginx.vm.network "forwarded_port", host: 8081, guest: 80
    nginx.vm.hostname = "nginx"
    nginx.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y ca-certificates curl gnupg
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      chmod a+r /etc/apt/keyrings/docker.gpg
      echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      cp /vagrant/docker-compose.yml /home/vagrant/
      cd /home/vagrant && docker compose up
    SHELL
    nginx.vm.provision "shell", run: "always", inline: "route add default gw 172.16.50.254"    
  end

  config.vm.define "zabbix" do |zab|
    zab.vm.network "public_network", bridge: "enp1s2", ip: "172.16.50.30", netmask: "255.255.255.0"
    zab.vm.hostname = "zabbix"
    zab.vm.provision "shell", inline: <<-SHELL
      wget https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb
      dpkg -i zabbix-release_6.4-1+debian12_all.deb
      apt-get update
      apt-get install -y zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent mariadb-server mariadb-client
      mysql -uroot -pa -e "create database zabbix character set utf8mb4 collate utf8mb4_bin;"
      mysql -uroot -pa -e "create user zabbix@localhost identified by \'mandarine\';"
      mysql -uroot -pa -e "grant all privileges on zabbix.* to zabbix@localhost;"
      mysql -uroot -pa -e "set global log_bin_trust_function_creators = 1;"
      zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -pmandarine zabbix
      mysql -uroot -pa -e "set global log_bin_trust_function_creators = 0;"
      echo "DBPassword = mandarine">> /etc/zabbix/zabbix_server.conf
      rm /etc/localtime
      ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
      echo "fr_FR.UTF-8 UTF-8">>/etc/locale.gen
      locale-gen
      cp /vagrant/apache_conf_zabbix /etc/apache2/sites-enabled/000-default.conf
      systemctl restart zabbix-server zabbix-agent apache2 mysql
      systemctl enable zabbix-server zabbix-agent apache2 mysql
    SHELL
  end




end
