

* Sommaire :toc:
- [[#plan][Plan]]
  - [[#r0][R0]]
  - [[#r1][R1]]
  - [[#s1][S1]]
  - [[#s2][S2]]
  - [[#s3][S3]]
- [[#configuration-routeurs][Configuration routeurs]]
  - [[#r1-1][R1]]
  - [[#routeurs-en-vm][Routeurs en vm]]
- [[#configuration-switch][Configuration Switch]]
  - [[#s1-1][S1]]
  - [[#s2-1][S2]]
  - [[#s3-1][S3]]
- [[#nfs][NFS]]
- [[#ldap][LDAP]]
- [[#serveur-web][Serveur web]]
- [[#mail][MAIL]]

* Plan

** R0

Routers + Retours de S1 + DMZ

| port              | host               | vm (IP/Masque)                                |
|-------------------+--------------------+-----------------------------------------------|
| GiabitEthernet0/1 | douglas01          | RTR1-FAI (10.10.10.6/29), NS1 (10.10.10.3/29) |
| GiabitEthernet0/2 | douglas02          | RTR2-FAI (10.10.10.6/29), NS2 (10.10.10.2/29) |
| GiabitEthernet0/3 | R1                 |                                               |
| GiabitEthernet0/4 | S1                 |                                               |
| GiabitEthernet0/5 | S1                 |                                               |
| GiabitEthernet0/6 | S1                 |                                               |
| GiabitEthernet0/7 | Raspberry PI (DMZ) | 10.10.10.1                                    |

** R1

Routeur vers les réseaux privés

| port          | host        |            IP |    Masque Réseau |
|---------------+-------------+---------------+------------------|
| FastEthernet0 | S2 (Vlan10) | 172.16.50.254 |    255.255.255.0 |
| FastEthernet1 | S3 (Vlan20) | 172.16.51.254 |    255.255.255.0 |
| FastEthernet4 | R0          |    10.10.10.5 | 255.2255.255.248 |

** S1

Brassage

| port            | host  |
|-----------------+-------|
| FastEthernet0/3 | R0    |
| FastEthernet0/4 | baie2 |
| FastEthernet0/5 | R0    |
| FastEthernet0/6 | baie3 |
| FastEthernet0/7 | R0    |
| FastEthernet0/8 | baie4 |

** S2

Service Informatique

| port            | host         |           IP | Masque Réseau |
|-----------------+--------------+--------------+---------------|
| FastEthernet0/1 | R1           | 172.16.51.10 | 255.255.255.0 |
| FastEthernet0/2 | douglas03    |  172.16.50.2 | 255.255.255.0 |
| FastEthernet0/2 | VM NFS       |  172.16.50.5 | 255.255.255.0 |
| FastEthernet0/3 | Raspberry PI |         DHCP | 255.255.255.0 |

** S3

Administration

| port            | host      |           IP | Masque Réseau |
|-----------------+-----------+--------------+---------------|
| FastEthernet0/1 | R1        | 172.16.51.10 | 255.255.255.0 |
| FastEthernet0/2 | douglas04 |  172.16.51.2 | 255.255.255.0 |

* Configuration routeurs

** R1

#+begin_src
enable
configure terminal
ip route 10.10.10.8 255.255.255.248 10.10.10.6
ip route 10.10.10.16 255.255.255.248 10.10.10.6
ip route 10.10.10.24 255.255.255.248 10.10.10.6
ip route 172.16.50.0 255.255.255.0 172.16.50.10
ip route 172.16.51.0 255.255.255.0 172.16.51.10
ip route 0.0.0.0 0.0.0.0 10.10.10.6
ip default-gateway 10.10.10.6
ip name-server 10.10.10.3
ip name-server 10.10.10.2

interface FastEthernet0
  switchport access vlan 10
  no ip address

interface FastEthernet1
  switchport access vlan 20
  no ip address

interface FastEthernet4
  ip address 10.10.10.5 255.255.255.248
  ip nat outside
  ip virtual-reassembly in
  duplex auto
  speedauto
  no shutdown

interface Vlan10
  ip address 172.16.50.254 255.255.255.0
  ip access-group 100 in

interface Vlan20
  ip address 172.16.51.254 255.255.255.0
  ip access-group 100 in

acces-lists 100 deny ip 10.10.10.0 0.0.0.255 any
#+end_src

=10.10.10.3= correspond à l'addresse de =NS1=
=10.10.10.2= correspond à l'addresse de =NS2=

** Routeurs en vm

=RTR1-FAI= et =RTR2-FAI= sont dans un cluster géré par =corosync= ([[file:rtr_fai/config/corosync/corosync.conf][config ici]]), si jamais =RTR1-FAI= tombe en panne, =RTR2-FAI= prends le relai.

*** Firewall

Le firewall utilisé est =ufw= avec les règles suivantes :

| To                    | Action    | From                  | Comment        |
|-----------------------+-----------+-----------------------+----------------|
| 22                    | ALLOW     | Anywhere              | # SSH_LOCAL    |
| 80                    | ALLOW     | Anywhere              | # HTTP         |
| 443                   | ALLOW     | Anywhere              | # HTTPS        |
| Anywhere on eth1      | ALLOW FWD | 10.10.10.0/24 on eth1 | # PUBLIC       |
| 80 on eth0            | ALLOW FWD | 10.10.10.0/24 on eth1 | # HTTP_EXT     |
| 443 on eth0           | ALLOW FWD | 10.10.10.0/24 on eth1 | # HTTPS_EXT    |
| 9.9.9.9 53 on eth0    | ALLOW FWD | 10.10.10.3 on eth1    | # DNS_RECURSIF |
| 9.9.9.9 53 on eth0    | ALLOW FWD | 10.10.10.2 on eth1    | # DNS_RECURSIF |
| 10.10.10.3 53 on eth1 | ALLOW FWD | 10.10.10.0/24 on eth1 | # DNS          |
| 0.0.0.0 53 on eth0    | ALLOW FWD | 10.10.10.0/24 on eth1 | # DNS          |
| 9.9.9.9 53 on eth0    | ALLOW FWD | 10.10.10.0/24 on eth1 | # DNS          |

Il est déployé par un [[file:rtr_fai/config/filtrage.sh][script]] qui se lance à la création de la vm.

* Configuration Switch

** S1

#+begin_src
interface FastEthernet0/3
  switchport mode access
  switchport access vlan 20
interface FastEthernet0/4
  switchport mode trunk
  switchport trunk allowed vlan 20
interface FastEthernet0/5
  switchport mode access
  switchport access vlan 30
interface FastEthernet0/6
  switchport mode trunk
  switchport trunk allowed vlan 30
interface FastEthernet0/7
  switchport mode access
  switchport access vlan 40
interface FastEthernet0/8
  switchport mode trunk
  switchport trunk allowed vlan 40
#+end_src

** S2

S2 sert aussi de serveur dhcp pour le coté informatique.

#+begin_src
ip dhcp excludedaddress 172.16.50.1 172.16.50.20
ip dhcp excludedaddress 172.16.50.254 172.16.50.254
ip dhcp pool info
    network 172.16.50.0 255.255.255.0
    default-router 172.16.50.254
Interface range FastEthernet0/1 - 3
    switchport access vlan 10
    switchport mode access

Interface Vlan10
    ip address 172.16.50.10 255.255.255.0

ip default-gateway 172.16.50.254
ip name-server 10.10.10.3
ip name-server 10.10.10.2
#+end_src

** S3

 S3 sert aussi de serveur dhcp pour l'administration.

#+begin_src
ip dhcp excludedaddress 172.16.51.1 172.16.51.20
ip dhcp excludedaddress 172.16.51.254 172.16.51.254
ip dhcp pool admin
    network 172.16.51.0 255.255.255.0
    default-router 172.16.51.254
Interface range FastEthernet0/1 - 2
    switchport access vlan 20
    switchport mode access

Interface Vlan20
    ip address 172.16.51.10 255.255.255.0

ip default-gateway 172.16.51.254
ip name-server 10.10.10.3
ip name-server 10.10.10.2
#+end_src

* NFS

Le serveur nfs se trouve sur la machine avec l'ip =172.16.50.5= et partage le dossier =/home=.

Pour pouvoir le monter (ce n'est pas encore fait automatiquement dans le /etc/fstab) il faut utiliser la commande =mount -t nfs 172.16.50.5:/home dossier= où dossier est le dossier dans lequel on veut monter le partage nfs.

Attention, seule les machines dans le réseau 172.16.50.0/24 peuvent monter le partage nfs.

* TODO LDAP

* TODO Serveur web

Il faut mettre une machine sur le switch 4 et y mettre le serveur web.

* TODO MAIL
