Vagrant.configure("2") do |config|

    config.vm.box = "debian/bookworm64"

  config.vm.define "ldap" do |ldap|
    ldap.vm.network "private_network", ip: "192.168.60.80"

    ldap.vm.provision "shell", inline: <<-SHELL
      apt-get update
    SHELL

  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.60.81"
    web.vm.network :forwarded_port, guest:80, host: 8080
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update 
      sudo apt-get install apache2 -y 
    SHELL

  end


end
