Vagrant.configure("2") do |config|
  config.vm.define "quartz" do |quartz|
    quartz.vm.box = "debian/bookworm64"
    quartz.vm.hostname = "quartz"

    quartz.vm.network "public_network", bridge: "enp1s2", virtualbox__intnet: "enp1s2" , use_dhcp_assigned_default_route: true
    quartz.vm.provision "shell", inline: <<-SHELL
     apt-get update
     SHELL
  end
end