Vagrant.configure("2") do |config|
  config.vm.define "resolve" do |resolve|
    resolve.vm.box = "debian/bookworm64"
    resolve.vm.hostname = "resolve"

    resolve.vm.network "public_network", bridge: "enp1s2", virtualbox__intnet: "enp1s2" , use_dhcp_assigned_default_route: true
    resolve.vm.provision "shell", inline: <<-SHELL
     apt-get update
     SHELL
  end
end
