Vagrant.configure("2") do |config|
  config.vm.define "quartz" do |quartz|
    quartz.vm.box = "debian/bookworm64"
    quartz.vm.hostname = "quartz"

    quartz.vm.network "public_network", ip: "10.10.10.12", bridge: "enp1s2"
    quartz.vm.provision "file", source: "./iptables", destination: "/home/vagrant/iptables"
    quartz.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install iptables
     iptables-restore < /home/vagrant/iptables
     SHELL
  end
end