Vagrant.configure("2") do |config|

    config.vm.box = "debian/bookworm64"

  config.vm.define "ldap" do |ldap|
    ldap.vm.network "private_network", ip: "192.168.12.252"
    ldap.vm.synced_folder "./conf", "/home/vagrant/conf/"
    ldap.vm.provision "shell", inline: <<-SHELL
      apt-get update
      
    SHELL

  end
  
  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.12.240"
    #ldap.vm.synced_folder "./conf", "/home/vagrant/conf/"
    client.vm.provision "shell", inline: <<-SHELL
      apt-get update
    SHELL

  end
end
