# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
  
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "debian/bookworm64"
    config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
    config.vm.define "ns" do |ns|
      ns.vm.hostname = "dns"
      ns.vm.synced_folder "config/", "/tmp/config"
      ns.vm.synced_folder "zones/","/tmp/zones"
      ns.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y bind9 bind9utils
        cp /tmp/config/named.conf.options /etc/bind/named.conf.options
        cp /tmp/config/named.conf.local /etc/bind/named.conf.local
        cp /tmp/zones/db.* /var/lib/bind/
        chown bind:bind /var/lib/bind/db.*
        cat /tmp/config/rndc.key >> /etc/bind/rndc.key
        ip route del default
        ip route add default via 192.168.4.1
        systemctl restart named
       SHELL
      ns.vm.network "forwarded_port", guest: 53, host: 5353, protocol: "udp"
      ns.vm.network "public_network",bridge: "enp1s2", ip:"192.168.4.2", netmask: "255.255.255.0"
  
    end
  
  end