Vagrant.configure("2") do |config|

    config.vm.box = "debian/bookworm64"
         
      config.vm.define "calcedoine" do |calcedoine|
        calcedoine.vm.hostname = "calcedoine"
        calcedoine.vm.network "private_network", ip: "192.168.60.40"
        calcedoine.vm.provision "file", source: "./config", destination: "/home/vagrant/"
        calcedoine.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y squid
      sudo cp /home/vagrant/config/squid.conf /etc/squid/squid.conf
      sudo systemctl restart squid
    SHELL
    end
  end
  