Vagrant.configure("2") do |config|

    config.vm.define "opale" do |opale|
    opale.vm.hostname = "opale"
    opale.vm.box = "debian/bookworm64"
    
    opale.vm.network "private_network", ip: "192.168.60.20"
    #opale.vm.network "public_network", bridge: "enp1s2", virtualbox__intnet: "enp1s2" , use_dhcp_assigned_default_route: true

    opale.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y slapd ldap-utils debconf-utils

      ldapadd -x -D cn=admin,dc=syssko,dc=iut -H ldapi:/// -W -f syssko.ldif
    SHELL
  end
end