Vagrant.configure("2") do |config|

    config.vm.define "resolve" do |resolve|
    resolve.vm.hostname = "resolve"
    resolve.vm.box = "debian/bookworm64"
    
    resolve.vm.network "private_network", ip: "192.168.60.20"
    #resolve.vm.network "public_network", bridge: "enp1s2", virtualbox__intnet: "enp1s2" , use_dhcp_assigned_default_route: true

    resolve.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y slapd ldap-utils debconf-utils
    SHELL
  end
end