Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
  
    config.vm.define "RTR1-FAI" do |rtr1|
      rtr1.vm.hostname = "RTR1-FAI"
      rtr1.vm.network "public_network", bridge: "enp1s2", ip: "172.16.128.1", netmask: "255.255.255.252"
      rtr1.vm.synced_folder "../config/", "/home/vagrant/config"
      rtr1.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y corosync pacemaker crmsh ufw
        
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -p
  
        mkdir -p /etc/iptables 
        cp -r /home/vagrant/config/iptables/rules.v4 /etc/iptables/
        cp -r /home/vagrant/config/iptables/restore-iptables.service /usr/lib/systemd/system/
        systemctl start restore-iptables
        systemctl enable restore-iptables
        
        rm -rf /etc/corosync/*
        cp -r /home/vagrant/config/corosync/* /etc/corosync/
        systemctl restart corosync pacemaker
        
        crm configure property stonith-enabled=false
        crm configure property no-quorum-policy=ignore 
        crm configure primitive mandarine ocf:heartbeat:IPaddr2 params ip=10.10.10.6 cidr_netmask=29 nic=eth1 iflabel=VIP op monitor interval=30s timeout=20s
        crm configure primitive capsule ocf:heartbeat:IPaddr2 params ip=10.10.10.14 cidr_netmask=29 nic=eth1 iflabel=VIP op monitor interval=30s timeout=20s
        crm configure primitive techtonic ocf:heartbeat:IPaddr2 params ip=10.10.10.22 cidr_netmask=29 nic=eth1 iflabel=VIP op monitor interval=30s timeout=20s
        crm configure primitive cyssko ocf:heartbeat:IPaddr2 params ip=10.10.10.30 cidr_netmask=29 nic=eth1 iflabel=VIP op monitor interval=30s timeout=20s
        crm resource move mandarine RTR1-FAI
        crm resource move capsule RTR1-FAI
        crm resource move techtonic RTR1-FAI
        crm resource move cyssko RTR1-FAI

        bash /home/vagrant/config/filtrage.sh
        ip route add 172.16.50.0/24 via 10.10.10.5
        ip route add 172.16.51.0/24 via 10.10.10.5
        echo "nameserver 10.10.10.3 \nnameserver 10.10.10.2" > /etc/resolv.conf
      SHELL
    end
    


    config.vm.define "ns1" do |ns1|
      ns1.vm.network "public_network", bridge: "enp1s2", ip: "10.10.10.3", netmask: "255.255.255.248"
      ns1.vm.hostname = "NS1"
      ns1.vm.synced_folder "../config/", "/home/vagrant/config"
      ns1.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install bind9 ufw -y
          sed -i -r "s/127.0.0.1.*/127.0.0.1       ns1.iut ns1/g" /etc/hosts
          echo -e "nameserver 127.0.0.1\nsearch iut\ndomain iut" > /etc/resolv.conf
          cp -r /home/vagrant/config/NS/* /etc/bind
          cp -r /home/vagrant/config//NS/NS1/NS1-named.conf.local /etc/bind/named.conf.local
          systemctl restart named

          ufw allow 22 comment SSH_LOCAL
          ufw allow 53 comment DNS
          echo y|ufw enable
          echo "nameserver 10.10.10.3 \nnameserver 10.10.10.2" > /etc/resolv.conf
          ip route del default
          ip route add default dev eth1 
      SHELL
  end

end
