Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
  
    config.vm.define "RTR2-FAI" do |rtr2|
      rtr2.vm.hostname = "RTR2-FAI"
      rtr2.vm.network "public_network", bridge: "enp1s2", ip: "172.16.128.2", netmask: "255.255.255.252"
      rtr2.vm.synced_folder "../config/", "/home/vagrant/config"
      rtr2.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y corosync pacemaker crmsh ufw
        
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -p
        
        mkdir -p /etc/iptables 
        cp -r /home/vagrant/config/iptables/rules.v4 /etc/iptables/
        cp -r /home/vagrant/config/iptables/restore-iptables.service /usr/lib/systemd/system/
        systemctl start restore-iptables
        systemctl enable restore-iptables
        
        rm -rf /etc/corosync/*
        cp -r /home/vagrant/config/corosync/* /etc/corosync/
        systemctl restart corosync pacemaker

        bash /home/vagrant/config/filtrage.sh
        ip route add 172.16.50.0/24 via 10.10.10.5
        ip route add 172.16.51.0/24 via 10.10.10.5
        echo "nameserver 10.10.10.3 \nnameserver 10.10.10.2" > /etc/resolv.conf
      SHELL
    end
  


    config.vm.define "ns2" do |ns2|
      ns2.vm.network "public_network", bridge: "enp1s2", ip: "10.10.10.2", netmask: "255.255.255.248"
      ns2.vm.hostname = "NS2"
      ns2.vm.synced_folder "../config/", "/home/vagrant/config"
      ns2.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install bind9 ufw -y
          sed -i -r "s/127.0.0.1.*/127.0.0.1       ns2.iut ns2/g" /etc/hosts
          echo -e "nameserver 127.0.0.1\nsearch iut\ndomain iut" > /etc/resolv.conf
          cp -r /home/vagrant/config/NS/* /etc/bind
          cp -r /home/vagrant/config/NS/NS2/NS2-named.conf.local /etc/bind/named.conf.local
          systemctl restart named

          ufw allow 22 comment SSH_LOCAL
          ufw allow 53 comment DNS
          echo y|ufw enable
          echo "nameserver 10.10.10.3 \nnameserver 10.10.10.2" > /etc/resolv.conf
      SHELL
     end

end
