
Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
       
    config.vm.define "peridot" do |peridot|
  peridot.vm.hostname = "peridot"
  peridot.vm.network "public_network", bridge: "enp1s2", ip: "10.14.0.2"
  peridot.vm.provision "file", source: "./config", destination: "/home/vagrant/"
  peridot.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y isc-dhcp-server
    sudo cp /home/vagrant/config/dhcpd.conf /etc/dhcp/dhcpd.conf
    sudo cp /home/vagrant/config/isc-dhcp-server /etc/default/isc-dhcp-server
    sudo service isc-dhcp-server start
  SHELL
  end

    config.vm.define "topaze" do |topaze|
  topaze.vm.hostname = "topaze"
  topaze.vm.network "public_network", bridge: "enp1s2", use_dhcp_assigned_default_route: true
  end
end
