Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
       
    config.vm.define "labradorite" do |labradorite|
      labradorite.vm.hostname = "labradorite"
      labradorite.vm.network "public_network", bridge: "enp1s2", ip: "192.168.60.10", netmask: "255.255.255.0"
      labradorite.vm.provision "file", source: "./config", destination: "/home/vagrant/"
      labradorite.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y isc-dhcp-server
    sudo cp /home/vagrant/config/dhcpd.conf /etc/dhcp/dhcpd.conf
    sudo cp /home/vagrant/config/isc-dhcp-server /etc/default/isc-dhcp-server
    sudo service isc-dhcp-server start
    cp /home/vagrant/config/resolv.conf /etc/
  SHELL
  end

    config.vm.define "topaze" do |topaze|
  topaze.vm.hostname = "topaze"
  topaze.vm.network "public_network", bridge: "enp1s2"
  end
end
