Vagrant.configure("2") do |config|

	config.vm.define "welsh" do |welsh|
		welsh.vm.box = "debian/bookworm64"
		welsh.vm.provider :virtualbox do |vb|
  			vb.gui = true
		end
		
		welsh.vm.provider "virtualbox" do |v|
			v.memory = 2048
		end			

		welsh.vm.hostname = "welsh"
	
		welsh.vm.provision "shell", inline: <<-EOF
			apt update && sudo apt upgrade
			apt install -y task-xfce-desktop
			apt-get install -y virtualbox-guest-x11
			apt-get install -y firefox-esr thunderbird
			reboot	
		EOF
	end

end
